### ISSUE TITLE
NullpointerException

### ISSUE THREAD

**Issue by k9ert** [square/subzero#119]
I'm trying to follow through with
https://subzero.readthedocs.io/en/master/running_without_hsm/

I managed to get to the point where i want to merge the signatures.
I have these values:
```
Initial sign transaction request: 
EAAqSQotCiC8fxRx/4QV6z/aar+xwiBzC76fynpmV+0DAtuZjqXbuRAAGJBOIgQQABgAEgsIqEYQAhoEEAAYABgAIgApAAAAAAAAAAA=

Initial finalize response 1: 
EnEKb3RwdWJEOGI1WXlROFZqQ3lUbmdIbzE5Y1pWQ0RrWTNiTVRxWmZQVWRneDJCaUREY3VkeXhmaE5pMTNIalhxbkw1TEVaWDVHSG10eUJ0MW9QbmdLWW5xQWJWWXY5WnRxRFROVlJjb1dlN0pYY1BXVw==

Initial finalize response 2: 
EnEKb3RwdWJEOHc0ZVRra25MYTJSVGJWbUc4U2I4UFdueW5LQm5vRWtRck1qSlg5bktEY2JlTUxMM0w4RHRvbnJyeTlydFlGQXlyZ29IdGZob3FDWUVrRkFOdFRiYlk5ZzdFVDdGQWRoZGhrVWc1dTVWdg==

Initial finalize response 3: 
EnEKb3RwdWJEOXRpcHN6b201cVh6NmloYkpmMXZzWFR1N3RMOVlHWDQ5ZU1RM1dnc044NnZ4RnRYTjJCTmNoZDdHYm1CYm9OSFFUSDNpYXBvdmZXRFdyemlLdHl4azhKQVJjY0FTempnMkd1Skp6aGhqRQ==

Initial finalize response 4: 
EnEKb3RwdWJEOVIyNml4Q2RrRXk0ZjVvVGVvbzlkOVBmenRtVXZGYnI1U0sxZ1ZTM3BOQndEMVZvdE00NEhHQjczMTE1WU55a0R4a2pONnF2RHNBYnVNYmhFa1BMVG9Qa3FnSEJmSFJuaGNRZGJxdGpjWA==

Gateway xpub: (from source):
tpubDA3zCqbkh8BS1h3VGmB6VU1Cj638VJufBcDWSeZVw3aEE9rzvmrNoKyGFqDwr8d9rhf4sh

Sign transaction response 1: 
Gm0KawpHMEUCIQDmTIgUC+MCGKSr8Fz8/CtpU3hNGIt6ldZbB+OgsmPJ0wIgbWfPwkPKUyYgp6TS9ZMJZ9DhiIvZnmlPpz1XNG6OtA4SIBh0uyQREYaNMD3GzcCLI30XNHRvZ4vJD8cUExNtO9wd

Sign transaction response 2: 
Gm0KawpHMEUCIQCk/lWb2mq5iy5FNpk+sJfQ4vWFv/yuMz7ysrBvYmUfOwIgG+mglKdgQG+7naY9HT9m9eSoRaGisf8guvGj/GXRPg8SIBh0uyQREYaNMD3GzcCLI30XNHRvZ4vJD8cUExNtO9wd
```

When i click on "show final transaction", i get a NullPointer:
```

127.0.0.1 - - [05/Nov/2019:13:09:19 +0000] "GET /show-final-transaction?signTxRequest=EAAqSQotCiC8fxRx%2F4QV6z%2Faar%2BxwiBzC76fynpmV%2B0DAtuZjqXbuRAAGJBOIgQQABgAEgsIqEYQAhoEEAAYABgAIgApAAAAAAAAAAA%3D&finalizeResponses=EnEKb3RwdWJEOGI1WXlROFZqQ3lUbmdIbzE5Y1pWQ0RrWTNiTVRxWmZQVWRneDJCaUREY3VkeXhmaE5pMTNIalhxbkw1TEVaWDVHSG10eUJ0MW9QbmdLWW5xQWJWWXY5WnRxRFROVlJjb1dlN0pYY1BXVw%3D%3D&finalizeResponses=EnEKb3RwdWJEOHc0ZVRra25MYTJSVGJWbUc4U2I4UFdueW5LQm5vRWtRck1qSlg5bktEY2JlTUxMM0w4RHRvbnJyeTlydFlGQXlyZ29IdGZob3FDWUVrRkFOdFRiYlk5ZzdFVDdGQWRoZGhrVWc1dTVWdg%3D%3D&finalizeResponses=EnEKb3RwdWJEOXRpcHN6b201cVh6NmloYkpmMXZzWFR1N3RMOVlHWDQ5ZU1RM1dnc044NnZ4RnRYTjJCTmNoZDdHYm1CYm9OSFFUSDNpYXBvdmZXRFdyemlLdHl4azhKQVJjY0FTempnMkd1Skp6aGhqRQ%3D%3D&finalizeResponses=EnEKb3RwdWJEOVIyNml4Q2RrRXk0ZjVvVGVvbzlkOVBmenRtVXZGYnI1U0sxZ1ZTM3BOQndEMVZvdE00NEhHQjczMTE1WU55a0R4a2pONnF2RHNBYnVNYmhFa1BMVG9Qa3FnSEJmSFJuaGNRZGJxdGpjWA%3D%3D&gateway=tpubDA3zCqbkh8BS1h3VGmB6VU1Cj638VJufBcDWSeZVw3aEE9rzvmrNoKyGFqDwr8d9rhf4sh&signTxResponses=Gm0KawpHMEUCIQDmTIgUC%2BMCGKSr8Fz8%2FCtpU3hNGIt6ldZbB%2BOgsmPJ0wIgbWfPwkPKUyYgp6TS9ZMJZ9DhiIvZnmlPpz1XNG6OtA4SIBh0uyQREYaNMD3GzcCLI30XNHRvZ4vJD8cUExNtO9wd&signTxResponses=Gm0KawpHMEUCIQCk%2FlWb2mq5iy5FNpk%2BsJfQ4vWFv%2FyuMz7ysrBvYmUfOwIgG%2BmglKdgQG%2B7naY9HT9m9eSoRaGisf8guvGj%2FGXRPg8SIBh0uyQREYaNMD3GzcCLI30XNHRvZ4vJD8cUExNtO9wd HTTP/1.1" 500 110 "http://localhost:8080/assets/index.html" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0" 29
ERROR [2019-11-05 13:09:20,365] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 511de5ed00cb2830
! java.lang.NullPointerException: null
! at org.bitcoinj.crypto.DeterministicKey.deserialize(DeterministicKey.java:547)
! at org.bitcoinj.crypto.DeterministicKey.deserializeB58(DeterministicKey.java:530)
! at org.bitcoinj.crypto.DeterministicKey.deserializeB58(DeterministicKey.java:521)
! at com.squareup.subzero.shared.ColdWallet.lambda$new$0(ColdWallet.java:53)
! at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
! at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
! at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
! at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
! at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
! at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
! at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
! at com.squareup.subzero.shared.ColdWallet.<init>(ColdWallet.java:54)
! at com.squareup.subzero.server.resources.ShowFinalTransactionResource.request(ShowFinalTransactionResource.java:50)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:567)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:531)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
! at java.base/java.lang.Thread.run(Thread.java:835)
```

Any idea what might be wrong here? How can i track that down more efficiently?

**Comment by alokmenghrajani** [comment]
Thanks for the report. I'm going to investigate this next week.

**Comment by alokmenghrajani** [comment]
I have the feeling the gateway got truncated (it should be `tpubDA3zCqbkh8BS1h3VGmB6VU1Cj638VJufBcDWSeZVw3aEE9rzvmrNoKyGFqDwr8d9rhf4sh4Yjg8LVwkehVF3Aoyss1KdDFLoiarFJQvqp4R` instead of `tpubDA3zCqbkh8BS1h3VGmB6VU1Cj638VJufBcDWSeZVw3aEE9rzvmrNoKyGFqDwr8d9rhf4sh`).

I'm able to reproduce the NPE with a shortened gateway address and I am able to get a transaction with the full address.

I'll also add a check to make sure other people don't trip on this.

**Comment by alokmenghrajani** [comment]
I'll close this issue for now. Feel free to re-open if it's something else which was causing the stack trace and we can investigate further.
